version: '3.1'
services:
  php:
    restart: always
    build:
      context: ./                  # 指定dockerfile文件的所在路径  
      dockerfile: Dockerfile    # 指定Dockerfile文件名称 
    container_name: php
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/yixiong/wwwroot:/var/www/html
      - /home/yixiong/wwwlogs:/var/www/logs
      - /home/yixiong/yaconf:/var/www/yaconf
      - /home/yixiong/vhosts:/usr/local/nginx/conf/conf.d
    networks:
      tianpan_net:
        ipv4_address: 172.19.0.100
  mysql:
    # restart: always
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        TZ: Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
    command: 
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    ports:
      - 3306:3306
    networks:
      tianpan_net:
        ipv4_address: 172.19.0.3
  redis:
    # restart: always
    image: redis
    hostname: redis
    container_name: redis
    privileged: true
    volumes:
      - ./conf/redis.conf:/etc/redis.conf
    ports:
      - 6379:6379
    command: ["redis-server","/etc/redis.conf"]
    networks:
      tianpan_net:
        ipv4_address: 172.19.0.2
networks:
  tianpan_net:
    driver: bridge
    ipam:
       config:
        - subnet: 172.19.0.0/16
volumes:
  mysql_data:
