version: '3.1'
services:
  php:
    restart: always
    build:
      context: ./                  # 指定dockerfile文件的所在路径  
      dockerfile: Dockerfile    # 指定Dockerfile文件名称 
    container_name: php
    ports:
      - 80:80
      - 443:443
      - 9010:9010
    volumes:
      - /mnt/d/tianpan/project:/var/www/html
      - /home/yixiong/wwwroot/kfgj_api:/var/www/html/kfgj_api
      - /mnt/d/tianpan/vhosts:/usr/local/nginx/conf/conf.d
      - /mnt/d/tianpan/www/logs:/var/log/www
    networks:
      tianpan_net:
        ipv4_address: 172.19.0.100
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        TZ: Asia/Shanghai
    volumes:
      - /mnt/d/tianpan/mysql/logs:/var/log/mysql
      - mysql_data:/var/lib/mysql
    command: 
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      tianpan_net:
        ipv4_address: 172.19.0.3
  redis:
    restart: always
    image: redis
    hostname: redis
    container_name: redis
    privileged: true
    volumes:
      - /mnt/d/tianpan/redis/data:/data
      - ./conf/redis.conf:/etc/redis.conf
    ports:
      - 6379:6379
    command: ["redis-server","/etc/redis.conf"]
    networks:
      tianpan_net:
        ipv4_address: 172.19.0.2
networks:
  tianpan_net:
    driver: bridge
    ipam:
       config:
        - subnet: 172.19.0.0/16
volumes:
  mysql_data:
